app:
  threadPool:
    corePoolSize: 3
    maxPoolSize: 10
    queueCapacity: 11
spring:
  application:
    name: transaction-processor
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  server:
    port: 8080
  data:
    redis:
      host: localhost
      port: 6379
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    enable:
      all: true