app:
  threadPool:
    corePoolSize: 3
    maxPoolSize: 10
    queueCapacity: 11

spring:
  application:
    name: transaction-processor
  datasource:
    url: jdbc:postgresql://localhost:5432/transaction_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    prometheus:
      access: unrestricted
  metrics:
    enable:
      all: true
  server:
    port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

info:
  build:
    artifact: ${project.artifactId}
    version: ${project.version}
    time: ${maven.build.timestamp}
  app:
    name: ${spring.application.name}
    description: "Transaction processing application"
