global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'spring-actuator'
    static_configs:
      - targets: [ 'localhost:8081' ]
#    basic_auth:
#      username: 'admin'
#      password: 'admin'
